version: '3.4'
services:
  dockerserver:
    build: 
      context: .
      dockerfile: Dockerfile.local
      target: development
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run dev